### ISSUE TITLE
LIBUSB_ERROR_NOT_FOUND thrown

### ISSUE THREAD

**Issue by weisjohn** [weisjohn/guitar-controller#7]
```
$ nd example.js 
Error: LIBUSB_ERROR_NOT_FOUND
    at Device.Object.defineProperty.get (/Users/jweis/mysrc/weisjohn/guitar-controller/node_modules/usb/usb.js:44:67)
    at Device.usb.Device.open (/Users/jweis/mysrc/weisjohn/guitar-controller/node_modules/usb/usb.js:31:16)
    at /Users/jweis/mysrc/weisjohn/guitar-controller/index.js:89:16
    at Array.forEach (native)
    at module.exports (/Users/jweis/mysrc/weisjohn/guitar-controller/index.js:87:25)
    at Object.<anonymous> (/Users/jweis/mysrc/weisjohn/guitar-controller/example.js:1:99)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Object.nodeDevHook [as .js] (/Users/jweis/.nvm/v0.10.32/lib/node_modules/node-dev/lib/hook.js:44:7)
    at Module.load (module.js:356:32)
[ERROR] 00:56:31 Error
```

**Comment by weisjohn** [comment]
related to nonolith/node-usb#61, we should call `this.__claimInterface(0);`

**Comment by lishichao1002** [comment]
@weisjohn 

![image](https://user-images.githubusercontent.com/13584162/45874462-80180700-bdc7-11e8-962b-69fcd4d7a9e5.png)
